### ISSUE TITLE
Feature request - Populating device variables on first run that are assigned to pins d0-5

### ISSUE THREAD

**Issue by Windsinger1985** [Stationeers-ic/stationeers-code-simulator#15]
Hi,

Since it's not implemented, it would help populate the device variables without having to set it manually while adding the devices.

_**Goal: write or Paste a script, add the devices and run it once.**_
- If you request something from a device that you defined on let's say d0 (for example the light if it's `On` and what `Color`).
- check if those variables are defined on that device set on d0
- if not, add the variables with no content. (or 0) so the user can fill in the missing data.
- devices NOT assigned to a pin are skipped and not meant to be added obviously.

Side effect and something to consider, since you can add multiple devices on d0. this might cause other issues.
Perhaps make it impossible to add another device on an already assigned pin before proceeding.

**Comment by Traineratwot** [comment]
Complete.
