### ISSUE TITLE
Он обманщик

### ISSUE THREAD

**Issue by Alicricher** [Stationeers-ic/stationeers-code-simulator#16]
![shaman-o-voine](https://github.com/Stationeers-ic/stationeers-code-simulator/assets/126563834/9cd4b637-2cff-4801-8c57-32f4edde1e41)
Говорит что русский а пишет на пендоском

**Comment by Traineratwot** [comment]
Я РУССКИЙ МОЙ КРОВЬ ОТ ОТЦААААА
