### ISSUE TITLE
Device List Logic Transmitter

### ISSUE THREAD

**Issue by FrankSTUCKX** [Stationeers-ic/stationeers-code-simulator#24]
The  Device List is quite confusing organised, would be better with ingame namespace. (for instance LED small is LED5 here).
Having trouble to find the logic transmitter devices...

 great work however, amazing.

**Comment by Traineratwot** [comment]
it's a good idea, I can organize the grouping into the same categories, but you need to decide which categories they are.

I suggest  use the categorization from stationpedia

**Comment by Traineratwot** [comment]
I added localization from the game now you can search in your own and English languages. So how are you used to
p.s
reopen this issues if you think that this is not enough :)
