### ISSUE TITLE
Simplify the search for languages.

### ISSUE THREAD

**Issue by Superhuski** [Stationeers-ic/stationeers-code-simulator#26]
Would it be possible to take the language selection from the hidden side menu into the menu bar? maybe just as a dropdown with the flags to the left of the ResetAll button?

It would be more visible for many normal users than looking for it in the hidden side menu.

Thanks for the cool IC10 code simulator. Please keep it up.

Greetings Superhuski

**Comment by Traineratwot** [comment]
Of course, I'll do it next week. However, I am surprised that you are having problems, the language is detected automatically depending on the language of the system :)

if your language is not in the list yet, you can add it yourself. There is a link in the readme

**Comment by Traineratwot** [comment]
done :)
