### ISSUE TITLE
Direct ID Reference instructions making errors when used with constant

### ISSUE THREAD

**Issue by Benoit-Julien** [Stationeers-ic/stationeers-code-simulator#29]
Hello,
I'm using direct ID Reference instructions (ld, sd) with a constant and it make an error when I over the line.

Exemple:

```
define FurnaceId 511812

ld r0 FurnaceId Pressure
```
Error: Device with id "FurnaceId" not found at 0

**Comment by Traineratwot** [comment]
Thanks, I fix this bug
