### ISSUE TITLE
Device numbering removal bug

### ISSUE THREAD

**Issue by WORMSS** [Stationeers-ic/stationeers-code-simulator#30]
Hello, I seem to have got myself into a pickle with the device numbering..

I have not yet tried the absolute minimum requirements to make this happen, but I have taken a video of it happening with 1 chip housing and 2 additional battery devices. 

[Video 🎥 https://streamable.com/re15bv](https://streamable.com/re15bv)

Though, I am currently unsure if the 2nd battery is really required here, but it is what I currently had, and I wanted to document this first incase I forget how I got in this mess.

Step 1: Have the default chip housing.
Step 2: Add 2 Station Batteries, default everything, but add 1 battery has `d0`, and 1 as `d3` (no idea why I choice d3, just a whim)
Step 3: Refresh the browser. ❗ Observe they should STILL be the devices from before.
Step 4: Add `d1` to the `d0` battery, and observe they are both listed.
Step 5: Remove `d0` ⚠️ Observe they BOTH vanished ⚠️
Step 6: Re-add `d0` ❓ Observe `d1` has returned with no mention of `d0` ❓

**Comment by Traineratwot** [comment]
Thanks. Fixed.

**Comment by WORMSS** [comment]
Confirmed, thank you.
